### ISSUE TITLE
Problemas con las funciones   `POFx`

### ISSUE THREAD

**Issue by nepito** [IslasGECI/rapid_eradication_assessment#2]
Esta línea está causando problemas:
`shape <- as(tmpshape, "owin")`

Al correr el archivo `src/pairwise_simulations.R` obtenemos Na. Intentamos con la variable:
`poligono <- sp::polygons(tmpshape)`

## Referencias
- [sp](https://cran.r-project.org/web/packages/sp/sp.pdf)
- [inside.owin](https://www.rdocumentation.org/packages/spatstat/versions/1.64-1/topics/inside.owin)

**Comment by nepito** [comment]
Intentamos cambiar:
```
shape <- as(tmpshape, "owin")
```
por:
```
yrange = tmpshape@bbox["y",]
xrange = tmpshape@bbox["x",]
shape <- as.owin(list(xrange=xrange,yrange=yrange))
```
Y el resultado fue el mismo.

Otra opción es utilizar *maptools* por el siguiente comentario:
"Additional methods for `as.owin` are provided in the *maptools* package: `as.owin.SpatialPolygon`, `as.owin.SpatialPolygons`, `as.owin.SpatialPolygonsDataFrame`.

Así obtuvimos las cooredenadas de la variables `tmpshape`:
```
a[[1]]@Polygons[[1]]@coords
```

**Comment by islasfernando** [comment]
https://maptools.r-forge.r-project.org/reference/as.owin.html

**Comment by MemoOlv** [comment]
Al correr la instrucción `make run` se puede replicar el error de este _issue_
